export const PrimaryColor = "#E86E5A"
export const NeutralColor = "#000000"
export const SecundaryColor = "#b8b8b8"
export const SecondaryLight = "#ffffff"
export const NeutralSecundaryColor = "#C7C7CC"